build:
  cuda_version: "12.1.1"
  python_packages:
    - "accelerate==0.33.0"
    - "torch==2.4.0"
    - "transformers==4.44.0"
    - "diffusers==0.30.0"
    - "segment-anything-py==1.0.0"
    - "opencv-python-headless==4.10.0.82"
